### ISSUE TITLE
pip install bitfield failes

### ISSUE THREAD

**Issue by rocktavious** [stestagg/bitfield#3]
Hey,

I would like to try out the package/add it as a requirement to my own package but it appears to be failing with pip install

Here is the error i get:

cimpl\field.c(301) : fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

error: command '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\cl.exe"' failed with exit status 2

Here is the full pip log
------------------------------------------------------------
C:\Python27\Scripts\pip-script.py run on 07/16/13 14:26:04
Downloading/unpacking bitfield

  Getting page https://pypi.python.org/simple/bitfield/
  URLs to search for versions for bitfield:
  * https://pypi.python.org/simple/bitfield/
  Analyzing links from page https://pypi.python.org/simple/bitfield/
    Found link https://pypi.python.org/packages/source/b/bitfield/bitfield-1.2.tar.gz#md5=441129691d48dbe977a144d1b7e5931f (from https://pypi.python.org/simple/bitfield/), version: 1.2
    Found link https://pypi.python.org/packages/source/b/bitfield/bitfield-1.3.tar.gz#md5=3854e5b80907231639a96b8c68fbde6a (from https://pypi.python.org/simple/bitfield/), version: 1.3
    Found link https://pypi.python.org/packages/source/b/bitfield/bitfield-1.32.tar.gz#md5=7ddb172aba63417859b506816e6ee08a (from https://pypi.python.org/simple/bitfield/), version: 1.32
    Found link https://pypi.python.org/packages/source/b/bitfield/bitfield-1.0.tar.gz#md5=789d54350ed758a6c96210e4299d04fd (from https://pypi.python.org/simple/bitfield/), version: 1.0
    Found link https://pypi.python.org/packages/source/b/bitfield/bitfield-1.31.tar.gz#md5=a80d6c7ca4ec7e134944d22c46599b89 (from https://pypi.python.org/simple/bitfield/), version: 1.31
    Found link https://pypi.python.org/packages/source/b/bitfield/bitfield-1.1.tar.gz#md5=0abc203174331426eaee349c1a759192 (from https://pypi.python.org/simple/bitfield/), version: 1.1
  Using version 1.32 (newest of versions: 1.32, 1.31, 1.3, 1.2, 1.1, 1.0)
  Downloading from URL https://pypi.python.org/packages/source/b/bitfield/bitfield-1.32.tar.gz#md5=7ddb172aba63417859b506816e6ee08a (from https://pypi.python.org/simple/bitfield/)
  Running setup.py egg_info for package bitfield

    running egg_info
    creating pip-egg-info\bitfield.egg-info
    writing pip-egg-info\bitfield.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\bitfield.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\bitfield.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\bitfield.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    

    reading manifest file 'pip-egg-info\bitfield.egg-info\SOURCES.txt'
    writing manifest file 'pip-egg-info\bitfield.egg-info\SOURCES.txt'
  Source in c:\users\krockman\appdata\local\temp\pip-build-krockman\bitfield has version 1.32, which satisfies requirement bitfield
Installing collected packages: bitfield

  Running setup.py install for bitfield

    Running command C:\Python27\python.exe -c "import setuptools;__file__='c:\\users\\krockman\\appdata\\local\\temp\\pip-build-krockman\\bitfield\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\krockman\appdata\local\temp\pip-0ahjlk-record\install-record.txt --single-version-externally-managed
    running install
    running build
    running build_ext
    skipping 'cimpl\field.c' Cython extension (up-to-date)

    building 'bitfield' extension

    creating build
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\cimpl
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tccimpl\field.c /Fobuild\temp.win-amd64-2.7\Release\cimpl\field.obj -g

    cl : Command line warning D9002 : ignoring unknown option '-g'

    field.c

    cimpl\field.c(301) : fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

    error: command '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\cl.exe"' failed with exit status 2

    Complete output from command C:\Python27\python.exe -c "import setuptools;__file__='c:\\users\\krockman\\appdata\\local\\temp\\pip-build-krockman\\bitfield\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\krockman\appdata\local\temp\pip-0ahjlk-record\install-record.txt --single-version-externally-managed:

    running install

running build

running build_ext

skipping 'cimpl\field.c' Cython extension (up-to-date)

building 'bitfield' extension

creating build

creating build\temp.win-amd64-2.7

creating build\temp.win-amd64-2.7\Release

creating build\temp.win-amd64-2.7\Release\cimpl

C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tccimpl\field.c /Fobuild\temp.win-amd64-2.7\Release\cimpl\field.obj -g

cl : Command line warning D9002 : ignoring unknown option '-g'

field.c

cimpl\field.c(301) : fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

error: command '"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\amd64\cl.exe"' failed with exit status 2

----------------------------------------

Command C:\Python27\python.exe -c "import setuptools;__file__='c:\\users\\krockman\\appdata\\local\\temp\\pip-build-krockman\\bitfield\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\krockman\appdata\local\temp\pip-0ahjlk-record\install-record.txt --single-version-externally-managed failed with error code 1 in c:\users\krockman\appdata\local\temp\pip-build-krockman\bitfield

Exception information:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 139, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 271, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python27\lib\site-packages\pip\req.py", line 1185, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Python27\lib\site-packages\pip\req.py", line 592, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "C:\Python27\lib\site-packages\pip\util.py", line 662, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command C:\Python27\python.exe -c "import setuptools;__file__='c:\\users\\krockman\\appdata\\local\\temp\\pip-build-krockman\\bitfield\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\krockman\appdata\local\temp\pip-0ahjlk-record\install-record.txt --single-version-externally-managed failed with error code 1 in c:\users\krockman\appdata\local\temp\pip-build-krockman\bitfield

**Comment by stestagg** [comment]
Just seen this again on Windows 10

**Comment by Witiko** [comment]
Compilation fails with Python 3.7 on up-to-date Debian 10:

```
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -I/home/witiko/.virtualenvs/gensim/include/python3.7m -c cimpl/field.c -o build/temp.linux-x86_64-3.7/cimpl/field.o -g                          
    cimpl/field.c: In function ‘__pyx_pf_8bitfield_7IdsPage_6__contains__’:                                    
    cimpl/field.c:3181:56: warning: suggest parentheses around ‘-’ in operand of ‘&’ [-Wparentheses]           
       __pyx_v_chunk_bit = (((usize_t)1) << (__pyx_v_number & CHUNK_MASK));                                    
                                                            ^                                                  
    cimpl/field.c: In function ‘__pyx_f_8bitfield_7IdsPage_add’:                                               
    cimpl/field.c:3333:56: warning: suggest parentheses around ‘-’ in operand of ‘&’ [-Wparentheses]           
       __pyx_v_chunk_bit = (((usize_t)1) << (__pyx_v_number & CHUNK_MASK));                                    
                                                            ^                                                  
    cimpl/field.c: In function ‘__pyx_f_8bitfield_7IdsPage_remove’:                                            
    cimpl/field.c:3543:56: warning: suggest parentheses around ‘-’ in operand of ‘&’ [-Wparentheses]           
       __pyx_v_chunk_bit = (((usize_t)1) << (__pyx_v_number & CHUNK_MASK));                                    
                                                            ^                                                  
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_17__or__’:                                        
    cimpl/field.c:6937:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:6936:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:6935:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_19__ior__’:                                       
    cimpl/field.c:7024:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:7023:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:7022:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_21union’:                                         
    cimpl/field.c:7086:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:7085:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:7084:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_27__sub__’:                                       
    cimpl/field.c:7328:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:7327:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:7326:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_29__isub__’:                                      
    cimpl/field.c:7415:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:7414:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:7413:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_31__isub__’:                                      
    cimpl/field.c:7477:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:7476:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:7475:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_33__xor__’:                                       
    cimpl/field.c:7539:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:7538:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:7537:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_35__ixor__’:                                      
    cimpl/field.c:7602:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:7601:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:7600:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_37__and__’:                                       
    cimpl/field.c:7664:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:7663:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:7662:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_39__iand__’:                                      
    cimpl/field.c:7727:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:7726:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:7725:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_41update’:                                        
    cimpl/field.c:7925:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:7924:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:7923:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_43difference_update’:                             
    cimpl/field.c:8123:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:8122:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:8121:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_45symmetric_difference_update’:                   
    cimpl/field.c:8447:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:8446:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:8445:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_47symmetric_difference’:                          
    cimpl/field.c:8596:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:8595:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:8594:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_49intersection_update’:                           
    cimpl/field.c:8862:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:8861:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:8860:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_51intersection’:                                  
    cimpl/field.c:9012:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:9011:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:9010:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_53isdisjoint’:                                    
    cimpl/field.c:9143:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:9142:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:9141:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_55issubset’:                                      
    cimpl/field.c:9273:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:9272:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:9271:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_57issuperset’:                                    
    cimpl/field.c:9398:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:9397:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]     
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:9396:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]        
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_8Bitfield_69unpickle’:                                      
    cimpl/field.c:10342:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]      
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:10341:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]    
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:10340:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__pyx_pw_8bitfield_3unpickle_bitfield’:                                        
    cimpl/field.c:11908:7: warning: variable ‘__pyx_clineno’ set but not used [-Wunused-but-set-variable]      
       int __pyx_clineno = 0;                                                                                  
           ^~~~~~~~~~~~~                                                                                       
    cimpl/field.c:11907:15: warning: variable ‘__pyx_filename’ set but not used [-Wunused-but-set-variable]    
       const char *__pyx_filename = NULL;                                                                      
                   ^~~~~~~~~~~~~~                                                                              
    cimpl/field.c:11906:7: warning: variable ‘__pyx_lineno’ set but not used [-Wunused-but-set-variable]       
       int __pyx_lineno = 0;                                                                                   
           ^~~~~~~~~~~~                                                                                        
    cimpl/field.c: In function ‘__Pyx_GetException’:                                                           
    cimpl/field.c:13811:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?                                                                                             
         tmp_type = tstate->exc_type;                                                                          
                            ^~~~~~~~                                                                           
                            curexc_type                                                                        
    cimpl/field.c:13812:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?                                                                                           
         tmp_value = tstate->exc_value;                                                                        
                             ^~~~~~~~~                                                                         
                             curexc_value                                                                      
    cimpl/field.c:13813:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                                                                   
         tmp_tb = tstate->exc_traceback;                                                                       
                          ^~~~~~~~~~~~~                                                                        
                          curexc_traceback                                                                     
    cimpl/field.c:13814:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?                                                                                             
         tstate->exc_type = local_type;                                                                        
                 ^~~~~~~~                                                                                      
                 curexc_type                                                                                   
    cimpl/field.c:13815:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?                                                                                           
         tstate->exc_value = local_value;                                                                      
                 ^~~~~~~~~                                                                                     
                 curexc_value                                                                                  
    cimpl/field.c:13816:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                                                                   
         tstate->exc_traceback = local_tb;                                                                     
                 ^~~~~~~~~~~~~                                                                                 
                 curexc_traceback                                                                              
    cimpl/field.c: In function ‘__Pyx_ExceptionSave’:                                                          
    cimpl/field.c:14009:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?                                                                                             
         *type = tstate->exc_type;                                                                             
                         ^~~~~~~~                                                                              
                         curexc_type                                                                           
    cimpl/field.c:14010:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?                                                                                           
         *value = tstate->exc_value;                                                                           
                          ^~~~~~~~~                                                                            
                          curexc_value                                                                         
    cimpl/field.c:14011:19: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                                                                   
         *tb = tstate->exc_traceback;                                                                          
                       ^~~~~~~~~~~~~                                                                           
                       curexc_traceback                                                                        
    cimpl/field.c: In function ‘__Pyx_ExceptionReset’:                                                         
    cimpl/field.c:14023:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?                                                                                             
         tmp_type = tstate->exc_type;                                                                          
                            ^~~~~~~~                                                                           
                            curexc_type                                                                        
    cimpl/field.c:14024:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?                                                                                           
         tmp_value = tstate->exc_value;                                                                        
                             ^~~~~~~~~                                                                         
                             curexc_value                                                                      
    cimpl/field.c:14025:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                                                                   
         tmp_tb = tstate->exc_traceback;                                                                       
                          ^~~~~~~~~~~~~                                                                        
                          curexc_traceback                                                                     
    cimpl/field.c:14026:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?                                                                                             
         tstate->exc_type = type;                                                                              
                 ^~~~~~~~
                 curexc_type
    cimpl/field.c:14027:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
         tstate->exc_value = value;
                 ^~~~~~~~~
                 curexc_value
    cimpl/field.c:14028:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
         tstate->exc_traceback = tb;
                 ^~~~~~~~~~~~~
                 curexc_traceback
    At top level:
    cimpl/field.c:7412:18: warning: ‘__pyx_pw_8bitfield_8Bitfield_29__isub__’ defined but not used [-Wunused-function]
     static PyObject *__pyx_pw_8bitfield_8Bitfield_29__isub__(PyObject *__pyx_v_x, PyObject *__pyx_v_y) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
```
